default_platform(:android)

platform :android do
  desc "Build APK for testing"
  lane :build_apk do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
  end

  desc "Build AAB for Release"
  lane :build_aab do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
  end

  desc "Deploy a new version to the Google Play Store (Internal Track)"
  lane :deploy do
    build_aab
    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab'
    )
  end
end
